use std::collections::HashMap;use std::path::{Path,PathBuf};use std::process::Stdio;use std::sync::{Arc,Mutex,OnceLock};use std::sync::atomic::{AtomicBool,Ordering};use tokio::io::{AsyncBufReadExt,AsyncWriteExt,BufReader};
pub struct Seat{pub id:&'static str,pub exe:&'static str,pub label:&'static str,pub hint:&'static str,pub get:&'static str,pub paths:&'static [&'static str],pub models:&'static [&'static str]}
pub const SEATS:&[Seat]=&[
Seat{id:"claude-code",exe:"claude",label:"Claude Code",hint:"Sign in with your Claude subscription: run `claude` once in a terminal",get:"claude.com/download",paths:&["~/.local/bin/claude.exe","~/.local/bin/claude","~/AppData/Local/Programs/claude/claude.exe","~/AppData/Roaming/npm/claude.cmd","/usr/local/bin/claude","/opt/homebrew/bin/claude"],models:&["default","sonnet","opus","haiku"]},
Seat{id:"codex",exe:"codex",label:"Codex CLI",hint:"Sign in with your ChatGPT subscription: `codex login`",get:"npm i -g @openai/codex",paths:&["~/.codex/bin/codex.exe","~/AppData/Roaming/npm/codex.cmd","~/.local/bin/codex","/usr/local/bin/codex","/opt/homebrew/bin/codex"],models:&["default","gpt-5-codex","gpt-5","o4-mini"]},
Seat{id:"grok-cli",exe:"grok",label:"Grok CLI",hint:"Sign in with your xAI account: run `grok` once",get:"npm i -g @vibe-kit/grok-cli",paths:&["~/.grok/bin/grok.exe","~/.grok/bin/grok","~/AppData/Roaming/npm/grok.cmd","/usr/local/bin/grok","/opt/homebrew/bin/grok"],models:&["default"]},
Seat{id:"antigravity",exe:"agy",label:"Antigravity",hint:"Sign in with your Google account: run `agy` once",get:"antigravity.google",paths:&["~/AppData/Local/agy/bin/agy.exe","~/.agy/bin/agy","~/.local/bin/agy","/usr/local/bin/agy","/opt/homebrew/bin/agy"],models:&["default"]},
Seat{id:"copilot",exe:"copilot",label:"GitHub Copilot CLI",hint:"Sign in with your GitHub Copilot subscription: run `copilot` once",get:"npm i -g @github/copilot",paths:&["~/AppData/Roaming/npm/copilot.cmd","~/.local/bin/copilot","/usr/local/bin/copilot","/opt/homebrew/bin/copilot"],models:&["default","claude-sonnet-4.5","gpt-5"]},
Seat{id:"cursor",exe:"cursor-agent",label:"Cursor CLI",hint:"run `cursor-agent login` (not `agent login`, that opens Grok Build) or set CURSOR_API_KEY",get:"cursor.com/cli",paths:&["~/AppData/Local/cursor-agent/cursor-agent.cmd","~/.cursor/bin/cursor-agent.exe","~/.local/bin/cursor-agent","/usr/local/bin/cursor-agent","/opt/homebrew/bin/cursor-agent"],models:&["auto","composer-2.5","cursor-grok-4.6-fast","cursor-grok-4.6-high-fast"]},
Seat{id:"opencode",exe:"opencode",label:"OpenCode",hint:"Free and model-agnostic: bring any provider you already pay for",get:"npm i -g opencode-ai",paths:&["~/.opencode/bin/opencode.exe","~/AppData/Roaming/npm/opencode.cmd","~/.local/bin/opencode","/usr/local/bin/opencode","/opt/homebrew/bin/opencode"],models:&["default"]}];
pub fn seat(id:&str)->Option<&'static Seat>{SEATS.iter().find(|s|s.id==id)}
pub fn is_seat(id:&str)->bool{seat(id).is_some()}
fn expand(p:&str)->PathBuf{p.strip_prefix("~/").map(|r|dirs::home_dir().unwrap_or_default().join(r)).unwrap_or_else(||PathBuf::from(p))}
fn exts()->&'static [&'static str]{if cfg!(windows){&[".exe",".cmd",".bat"]}else{&[""]}}
fn in_path(exe:&str)->Option<PathBuf>{let sep=if cfg!(windows){';'}else{':'};std::env::var("PATH").ok()?.split(sep).filter(|d|!d.is_empty()).find_map(|d|exts().iter().map(|e|Path::new(d).join(format!("{exe}{e}"))).find(|p|p.is_file()&&(cfg!(windows)||p.metadata().map(|m|m.len()>0).unwrap_or(false))))}
pub fn find(s:&Seat)->Option<(PathBuf,&'static str)>{let ev=std::env::var(format!("AMNI_{}_PATH",s.exe.to_uppercase().replace('-',"_"))).ok().map(PathBuf::from).filter(|p|p.is_file());ev.map(|p|(p,"environment override")).or_else(||in_path(s.exe).map(|p|(p,"PATH"))).or_else(||s.paths.iter().map(|c|expand(c)).find(|p|p.is_file()).map(|p|(p,"known location")))}
pub fn status_json()->serde_json::Value{serde_json::json!({"seats":SEATS.iter().map(|s|{let f=find(s);serde_json::json!({"id":s.id,"label":s.label,"exe":s.exe,"installed":f.is_some(),"path":f.as_ref().map(|x|x.0.display().to_string()).unwrap_or_default(),"found_via":f.as_ref().map(|x|x.1).unwrap_or(""),"hint":s.hint,"get":s.get,"models":s.models})}).collect::<Vec<_>>()})}
fn pins()->&'static Mutex<HashMap<String,String>>{static P:OnceLock<Mutex<HashMap<String,String>>>=OnceLock::new();P.get_or_init(||Mutex::new(HashMap::new()))}
pub fn drop_pin(sid:&str){pins().lock().unwrap().remove(sid);}
pub fn has_pin(sid:&str)->bool{pins().lock().unwrap().contains_key(sid)}
fn mode_of(m:&str,auto:bool)->&'static str{match m{"plan"=>"plan","autonomous"|"auto"=>"auto",_=>if auto{"auto"}else{"edit"}}}
fn model_arg(m:&str)->Option<String>{let t=m.trim();(!t.is_empty()&&t!="default").then(||t.to_string())}
#[derive(Clone,Copy,PartialEq,Debug)]pub enum Feed{Stdin,Argv,File}
pub fn argv(s:&Seat,model:&str,mode:&str,auto:bool,cwd:&Path,pin:Option<&str>)->(Vec<String>,Feed){let m=mode_of(mode,auto);let mm=model_arg(model);let mut a:Vec<String>=Vec::new();match s.id{
"claude-code"=>{a.extend(["-p","--output-format","stream-json","--verbose","--include-partial-messages","--permission-mode",match m{"plan"=>"plan","auto"=>"bypassPermissions",_=>"acceptEdits"}].map(String::from));if let Some(x)=mm{a.extend(["--model".into(),x]);}if let Some(p)=pin{a.extend(["--resume".into(),p.into()]);}(a,Feed::Stdin)}
"codex"=>{a.extend(["exec","--skip-git-repo-check"].map(String::from));a.extend(match m{"plan"=>vec!["--sandbox".to_string(),"read-only".into()],"auto"=>vec!["--full-auto".to_string()],_=>vec!["--sandbox".to_string(),"workspace-write".into()]});if let Some(x)=mm{a.extend(["-m".into(),x]);}a.push("-".into());(a,Feed::Stdin)}
"grok-cli"=>{a.extend(["--prompt-file","{file}","--output-format","streaming-messages-json","--include-partial-messages","--no-memory","--no-subagents","--max-turns","12","--permission-mode",if m=="plan"{"plan"}else{"dontAsk"}].map(String::from));if let Some(x)=mm{a.extend(["--model".into(),x]);}(a,Feed::File)}
"antigravity"=>{a.extend(["-p","{prompt}","--output-format","json","--add-dir",&cwd.display().to_string(),"--dangerously-skip-permissions","--mode",if m=="plan"{"plan"}else{"accept-edits"}].map(String::from));if let Some(p)=pin{a.extend(["--conversation".into(),p.into()]);}if let Some(x)=mm{a.extend(["--model".into(),x]);}(a,Feed::Argv)}
"copilot"=>{a.extend(["-p","{prompt}"].map(String::from));if m!="plan"{a.push("--allow-all-tools".into());}if let Some(x)=mm{a.extend(["--model".into(),x]);}(a,Feed::Argv)}
"cursor"=>{a.extend(["-p","{prompt}","--trust","--output-format","text"].map(String::from));if let Some(x)=mm{a.extend(["--model".into(),x]);}(a,Feed::Argv)}
_=>{a.extend(["run","--auto","--format","json"].map(String::from));if let Some(x)=mm{a.extend(["-m".into(),x]);}a.push("-".into());(a,Feed::Stdin)}}}
pub fn transcript_prefix(messages:&[serde_json::Value],user_msg:&str)->String{let turns:Vec<String>=messages.iter().filter(|m|matches!(m["role"].as_str(),Some("user")|Some("assistant"))).filter_map(|m|m["content"].as_str().map(|c|(m["role"].as_str().unwrap_or("").to_string(),c.to_string()))).filter(|(_,c)|c!=user_msg).map(|(r,c)|format!("{}: {}",if r=="user"{"User"}else{"Assistant"},if c.chars().count()>1500{c.chars().take(1500).collect::<String>()+" …"}else{c})).collect();let tail:Vec<&String>=turns.iter().rev().take(8).collect::<Vec<_>>().into_iter().rev().collect();if tail.is_empty(){user_msg.to_string()}else{format!("Earlier in this conversation:\n{}\n\nNow the user says:\n{}",tail.iter().map(|s|s.as_str()).collect::<Vec<_>>().join("\n\n"),user_msg)}}
fn json_text(line:&str,sid_out:&mut Option<String>)->Option<String>{let d:serde_json::Value=serde_json::from_str(line.trim()).ok()?;if let Some(s)=d.get("session_id").and_then(|v|v.as_str()){if !s.is_empty(){*sid_out=Some(s.to_string());}}if let Some(s)=d.get("conversation_id").or(d.get("conversationId")).and_then(|v|v.as_str()){*sid_out=Some(s.to_string());}let t=d.get("type").and_then(|v|v.as_str()).unwrap_or("");if t=="result"{return d.get("result").and_then(|v|v.as_str()).map(|s|format!("\u{E000}{s}"));}if t=="stream_event"{let ev=&d["event"];if ev["type"]=="content_block_delta"&&ev["delta"]["type"]=="text_delta"{return ev["delta"]["text"].as_str().map(String::from);}return None;}if t=="assistant"{return None;}for k in ["text","content","response","output"]{if let Some(s)=d.get(k).and_then(|v|v.as_str()){return Some(s.to_string());}}if let Some(p)=d.get("part"){if p["type"]=="text"{return p["text"].as_str().map(String::from);}}None}
pub fn finalize(seat:&Seat,stdout:&str)->(String,Option<String>){let mut sid=None;let jsonish=matches!(seat.id,"claude-code"|"grok-cli"|"antigravity"|"opencode");if !jsonish{let mut t=stdout.trim().to_string();if seat.id=="codex"{if let Some(i)=t.rfind("\ncodex\n"){t=t[i+7..].trim().to_string();}}return (t,None);}let mut deltas=String::new();let mut finals:Vec<String>=Vec::new();for l in stdout.lines(){if let Some(t)=json_text(l,&mut sid){if let Some(r)=t.strip_prefix('\u{E000}'){finals.push(r.to_string());}else{deltas.push_str(&t);}}}let out=finals.last().cloned().filter(|s|!s.trim().is_empty()).unwrap_or(deltas);(if out.trim().is_empty(){stdout.trim().to_string()}else{out.trim().to_string()},sid)}
pub async fn run(seat:&'static Seat,model:&str,mode:&str,auto:bool,cwd:&Path,prompt:&str,amni_sid:&str,interrupt:Arc<AtomicBool>,tx:tokio::sync::mpsc::Sender<axum::response::sse::Event>)->Result<String,String>{let fallback=std::env::current_dir().unwrap_or_else(|_|PathBuf::from("."));let cwd:&Path=if cwd.is_dir(){cwd}else{&fallback};let (path,_how)=find(seat).ok_or_else(||format!("{} is not installed. Get it: {} . {}",seat.label,seat.get,seat.hint))?;let pin=pins().lock().unwrap().get(amni_sid).cloned();let (mut a,feed)=argv(seat,model,mode,auto,cwd,pin.as_deref());let mut tmp:Option<PathBuf>=None;let long=prompt.len()>2400;if feed==Feed::File||(feed==Feed::Argv&&long){let p=std::env::temp_dir().join(format!("amni_{}_{}.txt",seat.exe,uuid::Uuid::new_v4()));tokio::fs::write(&p,prompt).await.map_err(|e|e.to_string())?;let ptr=format!("Read the UTF-8 task file at this absolute path and complete it fully; reply with only your answer text: {}",p.display());for x in a.iter_mut(){if x=="{file}"{*x=p.display().to_string();}if x=="{prompt}"{*x=ptr.clone();}}tmp=Some(p);}else{for x in a.iter_mut(){if x=="{prompt}"{*x=prompt.to_string();}}}
let ps=path.display().to_string();let wrap=cfg!(windows)&&ps.to_lowercase().ends_with(".cmd")||ps.to_lowercase().ends_with(".bat");let mut cmd=if wrap{let mut c=tokio::process::Command::new("cmd");c.arg("/c").arg(&ps);c}else{tokio::process::Command::new(&ps)};cmd.args(&a).current_dir(cwd).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).env("AMNI_CODE","1").env("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC","1").env("DISABLE_TELEMETRY","1").env("DO_NOT_TRACK","1");
#[cfg(windows)]{cmd.creation_flags(0x08000000);}
let _=tx.send(axum::response::sse::Event::default().event("thinking").data(serde_json::json!({"text":format!("{} · {} in {}",seat.label,if pin.is_some(){"resuming session"}else{"starting"},cwd.display())}).to_string())).await;
let mut child=cmd.spawn().map_err(|e|format!("could not start {} ({} in {}): {e}",seat.label,ps,cwd.display()))?;
if let Some(mut si)=child.stdin.take(){if feed==Feed::Stdin{let body=prompt.to_string();tokio::spawn(async move{let _=si.write_all(body.as_bytes()).await;let _=si.shutdown().await;});}else{drop(si);}}
let stdout=child.stdout.take().ok_or("no stdout")?;let stderr=child.stderr.take();let txc=tx.clone();let sid_label=seat.label;let reader=tokio::spawn(async move{let mut out=String::new();let mut lines=BufReader::new(stdout).lines();let mut sid=None;while let Ok(Some(l))=lines.next_line().await{out.push_str(&l);out.push('\n');let shown=json_text(&l,&mut sid).map(|t|t.trim_start_matches('\u{E000}').to_string()).unwrap_or_else(||l.clone());let shown=shown.trim();if !shown.is_empty()&&!shown.starts_with('{'){let _=txc.send(axum::response::sse::Event::default().event("thinking").data(serde_json::json!({"text":format!("{} · {}",sid_label,shown.chars().take(160).collect::<String>())}).to_string())).await;}}out});
let err_task=tokio::spawn(async move{let mut e=String::new();if let Some(se)=stderr{let mut lines=BufReader::new(se).lines();while let Ok(Some(l))=lines.next_line().await{e.push_str(&l);e.push('\n');}}e});
let status=loop{tokio::select!{s=child.wait()=>break s.map_err(|e|e.to_string())?,_=tokio::time::sleep(std::time::Duration::from_millis(250))=>{if interrupt.load(Ordering::Relaxed){let _=child.kill().await;if let Some(p)=tmp.take(){let _=tokio::fs::remove_file(p).await;}return Err("interrupted".into());}}}};
let out=reader.await.unwrap_or_default();let err=err_task.await.unwrap_or_default();if let Some(p)=tmp.take(){let _=tokio::fs::remove_file(p).await;}
let (text,sid)=finalize(seat,&out);if let Some(s)=sid{pins().lock().unwrap().insert(amni_sid.to_string(),s);}
if text.is_empty(){let e=err.trim();return Err(if !status.success(){format!("{} exited with {} · {}",seat.label,status.code().unwrap_or(-1),e.chars().take(600).collect::<String>())}else{format!("{} produced no text · {}",seat.label,e.chars().take(600).collect::<String>())});}
Ok(text)}
#[cfg(test)]mod tests{use super::*;
#[test]fn seat_table_has_seven_subscription_clis(){assert_eq!(SEATS.len(),7);for s in SEATS{assert!(!s.paths.is_empty()&&!s.models.is_empty()&&!s.get.is_empty());}assert!(is_seat("claude-code")&&is_seat("codex")&&!is_seat("openai"));}
#[test]fn plan_mode_maps_to_read_only_flags(){let c=Path::new(".");let (a,f)=argv(seat("claude-code").unwrap(),"default","plan",false,c,None);assert!(a.windows(2).any(|w|w==["--permission-mode","plan"])&&f==Feed::Stdin&&!a.iter().any(|x|x=="--model"));let (a,_)=argv(seat("codex").unwrap(),"gpt-5","plan",true,c,None);assert!(a.windows(2).any(|w|w==["--sandbox","read-only"])&&a.windows(2).any(|w|w==["-m","gpt-5"])&&a.last().unwrap()=="-");let (a,_)=argv(seat("codex").unwrap(),"default","edit",true,c,None);assert!(a.iter().any(|x|x=="--full-auto"));for s in SEATS{let (a,_)=argv(s,"default","auto",true,c,None);assert!(!a.iter().any(|x|x=="--yolo"||x=="-f"||x=="--dangerously-bypass-approvals-and-sandbox"),"{}",s.id);}}
#[test]fn claude_pin_becomes_resume(){let (a,_)=argv(seat("claude-code").unwrap(),"opus","edit",false,Path::new("."),Some("abc"));assert!(a.windows(2).any(|w|w==["--resume","abc"])&&a.windows(2).any(|w|w==["--model","opus"])&&a.windows(2).any(|w|w==["--permission-mode","acceptEdits"]));}
#[test]fn stream_json_final_wins_and_pins_session(){let s=seat("claude-code").unwrap();let out="{\"type\":\"system\",\"session_id\":\"s-1\"}\n{\"type\":\"stream_event\",\"event\":{\"type\":\"content_block_delta\",\"delta\":{\"type\":\"text_delta\",\"text\":\"par\"}}}\n{\"type\":\"stream_event\",\"event\":{\"type\":\"content_block_delta\",\"delta\":{\"type\":\"text_delta\",\"text\":\"tial\"}}}\n{\"type\":\"result\",\"result\":\"# Done\\n\\nAll good.\"}\n";let (t,sid)=finalize(s,out);assert_eq!(t,"# Done\n\nAll good.");assert_eq!(sid.as_deref(),Some("s-1"));let (t2,_)=finalize(s,"{\"type\":\"stream_event\",\"event\":{\"type\":\"content_block_delta\",\"delta\":{\"type\":\"text_delta\",\"text\":\"only deltas\"}}}\n");assert_eq!(t2,"only deltas");}
#[test]fn codex_keeps_only_the_answer_after_its_chrome(){let (t,_)=finalize(seat("codex").unwrap(),"OpenAI Codex v1\n--------\nuser\nhello\ncodex\nThe **answer** is 4.\n");assert_eq!(t,"The **answer** is 4.");}
#[test]fn transcript_prefix_is_bounded_and_skips_current_turn(){let msgs:Vec<serde_json::Value>=(0..20).map(|i|serde_json::json!({"role":if i%2==0{"user"}else{"assistant"},"content":format!("turn {i} {}","x".repeat(2000))})).collect();let p=transcript_prefix(&msgs,"now");assert!(p.starts_with("Earlier in this conversation:")&&p.ends_with("\nnow")&&p.matches("turn ").count()==8&&p.contains(" …")&&!p.contains("turn 0 "));assert_eq!(transcript_prefix(&[],"solo"),"solo");}
#[test]fn find_rejects_bad_env_override(){std::env::set_var("AMNI_CLAUDE_PATH","C:/definitely/not/here.exe");let f=find(seat("claude-code").unwrap());assert!(f.map(|x|x.1!="environment override").unwrap_or(true));std::env::remove_var("AMNI_CLAUDE_PATH");}}
